name: Run packer build on a template file

on:
  push:
    branches: [ "main" ]
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Packer build
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: 'ami.hcl'
          #workingDir: 'ami'
          #varFile: 'variables.json'
        env:
          AWS_DEFAULT_REGION: us-west-1
