name: Run packer build on a template file

on:
  push:
    branches: [ "main" ]
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Packer build
        uses: ExitoLab/packer_build_action_aws@v0.2.10
        with:
          templateFile: 'ami.pkr.hcl'
          workingDir: '.'
          #varFile: 'variables.json'
        env:
          AWS_DEFAULT_REGION: us-west-1
          subnet_id: subnet-0d0f524427c523eb0
          

