name: build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: zip project file
        run: |
          cd /home/runner/work/webapp
          zip -r webapp /home/runner/work/webapp

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: webapp.zip

      - name: install packer
        run: sudo apt-get install packer
          
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ami.pkr.hcl
      
      # build artifact
      - name: build packer 
        run: |
          packer init ami.pkr.hcl 
          packer build ami.pkr.hcl  2>&1 | sudo tee /home/output.txt
        env:
          PACKER_LOG: 1
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}
          
      # configure aws credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: us-east-1

      - name: template update and autoscaling group refresh
        id: deploy
        run: |
          export amiKey=$(cat /home/output.txt | grep 'us-east-1: '| tail -n1 | cut -c12-32)
          echo $amiKey
          aws ec2 create-launch-template-version --launch-template-name myec23-launch-template --source-version '$Latest' --launch-template-data "ImageId=$amiKey"
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name myec23-asg --launch-template LaunchTemplateName=myec23-launch-template,Version='$Latest' 
          aws autoscaling start-instance-refresh --auto-scaling-group-name myec23-asg --strategy Rolling
          

