name: build application

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1      
      - uses: actions/checkout@v2
      
      # Step 8
      - name: zip project file
        run: |
          cd /home/runner/work/webapp
          zip -r webapp /home/runner/work/webapp
      
      # Step 9
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: webapp.zip
          
      # Step 10
      - name: install packer
        run: sudo apt-get install packer
      
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ami.pkr.hcl
      
      # build artifact
      - name: build packer 
        run: |
          packer init ami.pkr.hcl
          packer build ami.pkr.hcl
        env:
          PACKER_LOG: 1
