name: build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: zip project file
        run: |
          cd /home/runner/work/webapp
          zip -r webapp /home/runner/work/webapp

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: webapp.zip

      - name: install packer
        run: sudo apt-get install packer
          
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ami.pkr.hcl
      
      # build artifact
      - name: build packer 
        run: |
          packer init ami.pkr.hcl 
          packer build ami.pkr.hcl  -var 'access_key=${{ secrets.ACCESS_KEY }}' -var 'secret_key=${{ secrets.SECRET_KEY }}'
        env:
          PACKER_LOG: 1
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}

